# Jay Bhanushali - 60009200047
# TSA Lab 8 CNN
---
## Perform the following:
- Step 1: Import all the libraries from Keras for neural network architectures
- Step 2: Define a function that extracts features (lagged values)
- Step 3: Initializing Sequence, steps, and reshaping the output to input it to our CNN model.
- Step 4: Reshaping the X matrices.
- Step 5: Define the CNNmodel.
- Step 6: Implement CNN Model Fitting.
- Step 7: Predict the futurevalues.
- Step 8: Plot the graph the predicted values.

## Importing the libraries


In [3]:
from numpy import array
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from keras.models import Sequential
from keras.layers import Dense,Flatten
from keras.layers.convolutional import Conv1D,MaxPooling1D
from datetime import datetime

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Defining the function to extract the features and outputs from the sequence

In [6]:
def split_sequence(sequence,steps):
  features,output=list(),list()

  for start in range(len(sequence)):
    end_index=start+steps

    if end_index>len(sequence)-1:
      break
    
    sequence_x,sequence_y=sequence[start:end_index],sequence[end_index]

    features.append(sequence_x)
    output.append(sequence_y)
  
  return array(features),array(output)

## Initializing the sequence using the Close of the Microsoft Stock

In [4]:
df=pd.read_csv('/content/drive/MyDrive/Microsoft_Stock.csv')
df.head()

Date   Open   High    Low  Close    Volume
0  04-01-2015  40.60  40.76  40.31  40.72  36865322
1  04-02-2015  40.66  40.74  40.12  40.29  37487476
2  04-06-2015  40.34  41.78  40.18  41.55  39223692
3  04-07-2015  41.61  41.91  41.31  41.53  28809375
4  04-08-2015  41.48  41.69  41.04  41.42  24753438

In [7]:
sequence=df['Close']
steps=3 # choosong a step size of 3

features,output=split_sequence(sequence,steps)

print("The sequence is: ")
print(sequence)
print("The features are: ")
print(features)
print("The step size is: ",steps)
print("The output list is: ",output)

The sequence is: 
0        40.72
1        40.29
2        41.55
3        41.53
4        41.42
         ...  
1506    232.34
1507    236.48
1508    235.24
1509    231.85
1510    235.77
Name: Close, Length: 1511, dtype: float64
The features are: 
[[ 40.72  40.29  41.55]
 [ 40.29  41.55  41.53]
 [ 41.55  41.53  41.42]
 ...
 [235.46 232.34 236.48]
 [232.34 236.48 235.24]
 [236.48 235.24 231.85]]
The step size is:  3
The output list is:  [ 41.53  41.42  41.48 ... 235.24 231.85 235.77]


In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1511 entries, 0 to 1510
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    1511 non-null   object 
 1   Open    1511 non-null   float64
 2   High    1511 non-null   float64
 3   Low     1511 non-null   float64
 4   Close   1511 non-null   float64
 5   Volume  1511 non-null   int64  
dtypes: float64(4), int64(1), object(1)
memory usage: 71.0+ KB


In [9]:
fig = go.Figure(data=[go.Candlestick(x=df['Date'],
                open=df['Open'],
                high=df['High'],
                low=df['Low'],
                close=df['Close'])])

fig.show()

##Reshaping the 2D input into 3D input data

In [10]:
feature=1
X=features
X

The sHAPE OF FEATURES
(1508, 3, 1)
The features after reshaping is: 
[[[ 40.72]
  [ 40.29]
  [ 41.55]]

 [[ 40.29]
  [ 41.55]
  [ 41.53]]

 [[ 41.55]
  [ 41.53]
  [ 41.42]]

 ...

 [[235.46]
  [232.34]
  [236.48]]

 [[232.34]
  [236.48]
  [235.24]]

 [[236.48]
  [235.24]
  [231.85]]]


In [ ]:
features=features.reshape((features.shape[0],features.shape[1],feature))
print("The sHAPE OF FEATURES")
print(features.shape)
print("The features after reshaping is: ")
print(features)

In [15]:
X_train = features[:-500]
X_test = features[-500:]

Y_train = output[:-500]
Y_test = output[-500:]

## Definfing the CNN model

In [11]:
model=Sequential()
model.add(Conv1D(filters=64,kernel_size=2,activation='relu',input_shape=(steps,feature)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(100,activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam',loss='mse')


## Fitting the model

In [ ]:
model.fit(X_train,Y_train,epochs=1000,verbose=0)

##Running the model

In [ ]:
Y_pred=model.predict(X_test,verbose=0)

In [ ]:
plt.figure(figsize=(16,10))
plt.plot(Y_test, color='g')
plt.plot(Y_pred, color='r')
plt.show()