In [45]:
import numpy as np
import pandas as pd

In [34]:
X1 = np.array([[0,0],[0,1],[1,0],[1,1]])
X2 = np.array([0,1])

In [24]:
np.dot([[0,0],[0,1],[1,0],[1,1]],[1,1]) + -1

array([-1,  0,  0,  1])

In [37]:
np.dot(X1,[1,1])

array([0, 1, 1, 2])

In [35]:
X2.shape

(2,)

In [36]:
activation(X2*[-1] + 0)

[1, 0]

In [43]:
weights_biases ={
    'and' : {'w':[1,1 ],'b':-2},
    'or': {'w': [1,1], 'b':-1},
    'not': {'w':[-1],'b':0},
}

In [40]:
def activation(Y):
    Y_hat = []
    for y in Y:
        Y_hat.append(int(y >= 0))
    return Y_hat # 0 for negative otherwise positive

In [67]:
def perceptron(X, w, b):
    if X.shape == (2,):
        y_hat = X*w + b
    
    else:
        y_hat = np.dot(X,w) + b
    
    # print(y_hat)
    # print(activation(y_hat))
    return activation(y_hat)


In [23]:
X2*[-1]

array([ 0, -1])

In [20]:
X2*[1,0] + 0

array([0, 0])

In [64]:
df = pd.DataFrame(X1,columns=['X1','X2'])
df

X1  X2
0   0   0
1   0   1
2   1   0
3   1   1

In [68]:
and_ = weights_biases['and']
w,b = and_['w'], and_['b']
and_Y = perceptron(X1,w,b)
df['AND'] = and_Y


In [66]:
df

X1  X2  AND
0   0   0    0
1   0   1    0
2   1   0    0
3   1   1    1

In [72]:
or_ = weights_biases['or']
w,b = or_['w'], or_['b']
# print(X1)
or_Y = perceptron(X1,w,b)

In [73]:
df[['X1','X2','OR']]

X1  X2  OR
0   0   0   0
1   0   1   1
2   1   0   1
3   1   1   1

In [75]:
not_ = weights_biases['not']
w,b = not_['w'], not_['b']
# print(X1)
not_Y = perceptron(X2,w,b)
df2 = pd.DataFrame(X2,columns=['X'])
df2['NOT'] = not_Y
df2[['X','NOT']]

X  NOT
0  0    1
1  1    0